name: Snyk
description: Runs vulnerability scans on dependencies and docker images
author: https://github.com/seek-oss
requirements:
  - docker
  - jq
configuration:
  properties:
    SNYK_TOKEN:
      type: string
  required:
    - SNYK_TOKEN